### ISSUE TITLE
Tracking issue for missing APIs

### ISSUE THREAD

**Issue by arlyon** [arlyon/async-stripe#32]
API requests will be closed to keep the issue tracker clean and the issue will be added to this list. If it is unchecked, it is unaddressed. Any PR's addressing these will be handled speedily (I promise! :smile: )

- [ ] setup_intent_ext (#41)
- [x] Customer balance transaction API (#271)
- [x] Search customer API (#260)
- [x] Balance::retrieve (#280)

**Comment by kennetpostigo** [comment]
@arlyon hi, I actually just ran into this, as you made the ticket 9 minutes ago 😅. I need the `AccountLink` API's for stripe as i'm integrating stripe connect into the backend i'm working on.

You also have listed `payment_intent` but I see it in the API in the docs that it's available, is that wrong?

The Link to the stripe docs:
https://stripe.com/docs/api/account_links

Is there any shot these can get generated?

**Comment by arlyon** [comment]
The short answer is yes, that list is modules that are being generated, but aren't exported (yet). I have been working to try and simplify the code gen from the previous project but there's still a ways to go. For example, `payment_intent` exists in two places, one is generated and one is hand written so we need to figure out which is which.

The next step for that is to run tests in CI for modules that aren't being included.

468bc048111dfce347d8ccf5972f45d8fd50b567 addresses that at least partially!

**Comment by kennetpostigo** [comment]
@arlyon thank you, i'll start using master branch to get access to it. Do you want me to report back with how it goes using the AccountLink?

**Comment by kennetpostigo** [comment]
So I tried to use the repo as a dependency but i'm getting really funky errors when trying to do so. Here's my package json:
```toml
[package]
name = "platform"
version = "0.1.0"
authors = ["Kennet Postigo <kennetfpostigo@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
async-graphql = "2.5.2"
async-graphql-tide = "2.5.2"
async-std = { version = "1.9.0", features = ["attributes"] }
async-stripe = { git = "https://github.com/arlyon/stripe-rs", branch = "master", features = [ "runtime-async-std-surf" ] }
async-trait = "0.1.42"
bincode = "1.3.1"
chbs = "0.1.0"
chrono = "0.4.19"
dotenv = "0.15.0"
futures = "0.3.12"
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
lettre = { version = "0.10.0-alpha.5", features = ["async-std", "async-std1", "async-std1-rustls-tls"] }
serde = "1.0.123"
serde_json = "1.0.62"
sqlx = { version = "0.5.1", features = [ "runtime-async-std-native-tls", "postgres", "chrono", "migrate", "uuid" ] }
tide = "0.16.0"
```

The errors look like:
```rust
error[E0034]: multiple applicable items in scope
   --> /Users/postman/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.4/src/field.rs:307:25
    |
307 |         check("load", len, M::BITS);
    |                               ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /Users/postman/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.4/src/mem.rs:29:2
```

I'm not sure why this happens
