### ISSUE TITLE
async-stripe Does Not Compile on the Latest version of Rust.

### ISSUE THREAD

**Issue by aprettygoodprogramer** [arlyon/async-stripe#703]
### Describe the bug

The async-stripe library will not compile.

 error[E0432]: unresolved import `crate::resources::CheckoutSessionItem`
 --> C:\Users\user\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\async-stripe-0.41.0\src\resources\generated\quote.rs:9:27
  |
9 |     Account, Application, CheckoutSessionItem, ConnectAccountReference, Currency, Customer,
  |                           ^^^^^^^^^^^^^^^^^^^
  |                           |
  |                           no `CheckoutSessionItem` in `resources`
  |                           help: a similar name exists in the module: `CheckoutSession`

### To Reproduce

Make a Rust project

```bash
cargo new async-stripe-issue
```
Add the async-stripe dependency in the Cargo.toml

```toml
[package]
name = "async-stripe-issue"
version = "0.1.0"
edition = "2024"

[dependencies]
#Add this line
async-stripe = { version = "*", default-features = false, features = [
    "runtime-tokio-hyper",
    "billing",
] }
```
Then just run
```bash
cargo build
```
You will get the following error: 
 error[E0432]: unresolved import `crate::resources::CheckoutSessionItem`
 --> C:\Users\user\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\async-stripe-0.41.0\src\resources\generated\quote.rs:9:27
  |
9 |     Account, Application, CheckoutSessionItem, ConnectAccountReference, Currency, Customer,
  |                           ^^^^^^^^^^^^^^^^^^^
  |                           |
  |                           no `CheckoutSessionItem` in `resources`
  |                           help: a similar name exists in the module: `CheckoutSession`

### Expected behavior

The program should compile, and when run, it should print "Hello World!"

### Code snippets

```rust

```

### OS

Windows

### Rust version

1.87.0

### Library version

async-stripe 0.41.0

### API version

2025-04-30
